---
title: "Permitation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages(c("janitor"))
```


```{r cars}
library("knitr")
library("janitor")
library("tidyverse")
```


```{r}
set.seed(1)

df.permutation= tibble(control=rnorm(25, mean=5.5,sd=2),
                       experimental= rnorm(25, mean=4.5, sd=1.5)) %>%
  pivot_longer(cols= everything(),
               names_to= "condition",
               values_to="performance")
```

```{r}
df.permutation
```
```{r}
ggplot(data = df.permutation, 
       mapping = aes(x = condition, y = performance)) +
  geom_point(position = position_jitter(height = 0, width = 0.1),
             alpha = 0.5) + 
  stat_summary(fun.data = mean_cl_boot, 
               geom = "linerange", 
               size = 1) +
  stat_summary(fun.y = "mean", 
               geom = "point", 
               shape = 21, 
               color = "black", 
               fill = "white", 
               size = 4) +
  scale_y_continuous(breaks = 0:10,
                     labels = 0:10,
                     limits = c(0, 10))

```
```{r}
difference_actual = df.permutation%>%
  group_by(condition) %>%
  summarize(mean = mean(performance)) %>%
  pull(mean) %>%
  diff()

difference_actual
```

```{r}
set.seed(1)
df.permutation =df.permutation %>%
  mutate(permutation = sample(condition))

df.permutation %>% 
  group_by(permutation) %>%
  summarize(mean = mean(performance), sd=sd(performance)) %>%
  ungroup() %>%
  summarize(diff=diff(mean))
```

```{r}
n_permutations = 10000

func_permutations = function(df){
  df %>% 
    mutate(condition = sample(condition)) %>%
    group_by(condition) %>%
    summarize(mean = mean(performance)) %>% 
    pull(mean) %>%
    diff()
}

df.permutations =tibble(
  permutation= 1:n_permutations,
  mean_difference = replicate(n=n_permutations, func_permutations(df.permutation))
)
```

```{r}
ggplot(data = df.permutations, aes(x= mean_difference))+
  geom_histogram(aes(y=stat(density)),
                 color= "black",
                 fill = "lightblue") + 
  stat_density(geom = "line",
               size = 1.5) +
  geom_vline(xintercept = difference_actual, color ="red", size = 2)
```
```{r}
pvalue = sum(df.permutations$mean_difference <= difference_actual)/ length(df.permutations$mean_difference)
pvalue
```

```{r}
#t-test
df.permutation = df.permutation %>%
  select(condition, performance)

a = df.permutation %>%
  filter(condition == "control")

b= df.permutation %>%
  filter(condition == "experimental")

t.test(a$performance, b$performance)
```

